FROM mhart/alpine-node:15.12.0 AS builder
WORKDIR /app
COPY ["package.json", "./"]
RUN npm install
COPY . .
CMD [ "npm", "run", "build"]


FROM mhart/alpine-node:15.12.0
WORKDIR /api
COPY --from=builder /app /api
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "development" ]; \
        then npm install; \
        else npm install --only=production; \
        fi
CMD [ "node", "./dist/server.js" ]