version: '3'
services:
  node-api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 4005:4005
    restart: always
    env_file:
      - ./.env
    environment:
      - PORT=4005
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.6
    env_file:
      - ./.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
